### ISSUE TITLE
Solve Default models?

### ISSUE THREAD

**Issue by azev77** [vfitoolkit/VFIToolkit-matlab#2]
Hi and thank you for this package!
Can your toolkit be used to solve default models (w/ nested value functions)?
For example: ([Matlab](https://github.com/vduarte/benchmarkingML/tree/master/Sovereign_Default/matlab) Duarte etal)

**Comment by robertdkirkby** [comment]
Can you please send link to a written up version of the model equations (rather than code implementing the model)?

**Comment by azev77** [comment]
https://julia.quantecon.org/multi_agent_models/arellano.html

**Comment by robertdkirkby** [comment]
Short answer: with VFI Toolkit you can solve the value fn problem, and the stationary distribution, but you could not use the built in commands to find the general equilibrium.

Instead of having a single price, e.g., the interest rate 'r' in Aiyagari (1994) you are solving for a price schedule q(B,y) in notation of link you sent above. (You could approximate q as a price at each grid point, but realistically you would assume a functional form, e.g., that q() is a quadratic function so it just has a few parameters.) What the general eqm commands in VFI Toolkit cannot presently handle is that this means that you need to evaluate the equilibrium pointwise (rather than just based on model aggregates). (Rather than pointwise, you could equivalently think of estimating the quadratic function params from the simulated model, and comparing them to those imputed as the general eqm condition.)

[Technically, it could be done using the VFI Toolkit general eqm commands, but would be a total mess and not an intelligent approach.]

Just FYI, some of the numbers in the original Arellano (2008) are not accurate [the main results are fine, just the numbers are not fully accurate]. See https://ideas.repec.org/a/red/issued/08-133.html for explanation.

I occasionally consider adding an option to solve this kind of problem to the general eqm commands, but it is not currently a priority so am yet to do so. [Is conceptually easy enough, just I have limited time.]
